name: simon_ai
description: Simon AI project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.22.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  design_system:
    path: ./design_system

  auto_route: 8.1.3
  cupertino_icons: 1.0.8
  dartx: 1.2.0
  dio: 5.4.3+1
  dotted_border: 2.1.0
  equatable: 2.0.5
  flutter_bloc: 8.1.5
  flutter_dotenv: 5.1.0
  flutter_native_splash: 2.4.0
  flutter_screenutil: 5.9.3
  flutter_secure_storage: 9.2.2
  flutter_web_browser: 0.17.1 # This can be removed
  freezed_annotation: 2.4.1
  get_it: 7.7.0
  google_fonts: 6.2.1
  intl: 0.19.0
  json_annotation: 4.9.0
  logger: 2.3.0
  material_color_generator: 1.1.0
  rxdart: 0.27.7
  shared_preferences: 2.2.3
  sqflite: 2.3.3+1
  stack_trace: 1.11.1
  stock: 1.1.1
  hive: 2.2.3
  path_provider: 2.1.3
  path_drawing: 1.0.1
  mutex: 3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: 8.0.0
  build_runner: 2.4.10
  dart_code_linter: 1.1.3

  flutter_flavorizr: 2.2.3
  flutter_gen_runner: 5.5.0+1
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  freezed: 2.5.2
  json_serializable: 6.8.0
  lints: 4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - environments/

flutter_gen:
  assets:
    exclude:
      - environments/*
      - assets/README.md

# Run command: flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icons/ic_launcher.png"
  image_path_ios: "icons/ic_launcher_ios.png" # Transparency not supported on IOS
  adaptive_icon_foreground: "icons/ic_launcher_foreground.png"
  adaptive_icon_background: "#ee1a64"
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false

flutter_native_splash:
  color: "#ffffff"
  image: "icons/splash_logo.png"
  android_12:
    image: "icons/splash_logo_android_12.png"
    branding: "icons/splash_branding.png"
