// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3JkVeivbsW3JFiOZbCT4GMGOLziRygWA',
    appId: '1:559870872327:web:25d0e4245edf4997c493a2',
    messagingSenderId: '559870872327',
    projectId: 'simonai-37870',
    authDomain: 'simonai-37870.firebaseapp.com',
    storageBucket: 'simonai-37870.appspot.com',
    measurementId: 'G-PNM399M52M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgLkQaXHLH76UA2evk9a9YrOeCEBwwLfA',
    appId: '1:559870872327:android:09c4e525e96fc105c493a2',
    messagingSenderId: '559870872327',
    projectId: 'simonai-37870',
    storageBucket: 'simonai-37870.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7pbwZJHND-k5tcxFdsVx5EF92_7h74q4',
    appId: '1:559870872327:ios:b26b8b37d473f6edc493a2',
    messagingSenderId: '559870872327',
    projectId: 'simonai-37870',
    storageBucket: 'simonai-37870.appspot.com',
    iosBundleId: 'com.xmartlabs.simonai.dev',
  );
}
